import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import DropdownMenu from "@/app/components/menu";
import Clock from "@/app/components/clock";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex flex-col min-h-screen font-[family-name:var(--font-geist-sans)] text-center">
          <header className="fixed top-0 left-0 w-full p-4 bg-gray-800 text-white flex justify-between items-center z-50">
              <Link href="/" className="hover:underline">
              <h1 className="text-xl font-bold">Mi Sitio</h1>
              </Link>
              <nav className="space-x-4">

                  <DropdownMenu />
              </nav>
          </header>

          <main className="flex-grow flex items-center justify-center w-full px-4">
              <div className="w-full max-w-5xl mx-auto mt-24 text-left">
                  {children}
              </div>
          </main>
          <footer className="fixed bottom-0 left-0 w-full p-4 bg-gray-800 text-white flex justify-between items-center z-50">
              <p className="text-sm">{new Date().getFullYear()} Mi Sitio</p>
              <div className="space-x-4">
                  <Clock/>
              </div>
          </footer>
      </div>
      </body>
    </html>
  );
}
